### ISSUE TITLE
Numpy.Empty - Not So Empty

### ISSUE THREAD

**Issue by rudrathegreat** [josephernest/wavfile.py#1]
Hi Joseph,

I have heard that Numpy.empty gives arrays that are not so empty. I have experimented with this myself using similar code to yours (minor changes from your code) which gave this result - 

```

[[ 2.96613498e-267]
 [-6.27289313e-043]
 [ 1.17767301e-268]
 [ 8.91241522e-313]]

```

In conclusion, `numpy.empty` arrays are no exactly empty. Any possible solution to the bug.

**Comment by josephernest** [comment]
Hello,

The fact that `np.empty` does not give a zero-filled array is not really a problem:

After https://github.com/josephernest/wavfile.py/blob/master/wavfile.py#L83:

    a = numpy.empty((len(data) // 3, 4), dtype='u1')

then all the data in the array is *rewritten*:

    a[:, :3] = data.reshape((-1, 3))
    a[:, 3:] = (a[:, 3 - 1:3] >> 7) * 255

so it's not a problem if `a` was filled with random data before.

**Comment by rudrathegreat** [comment]
ok. It's just that I am relatively new to NumPy, so I am still learning
